apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  AZURE_OPENAI_ENDPOINT: {{.Env.AZURE_OPENAI_ENDPOINT}}
  AZURE_OPENAI_35_TURBO_DEPLOYMENT_NAME: {{.Env.AZURE_OPENAI_35_TURBO_DEPLOYMENT_NAME}}
  AZURE_OPENAI_35_TURBO_MODEL_NAME: {{.Env.AZURE_OPENAI_35_TURBO_MODEL_NAME}}
  AZURE_OPENAI_API_VERSION: {{.Env.AZURE_OPENAI_API_VERSION}}
  AZURE_OPENAI_DEPLOYMENT_NAME: {{.Env.AZURE_OPENAI_DEPLOYMENT_NAME}}
  BING_SEARCH_ENDPOINT: {{.Env.BING_SEARCH_ENDPOINT}}
  BING_SEARCH_KEY: {{.Env.BING_SEARCH_KEY}}
  AZURE_SEARCH_ENDPOINT: {{.Env.AZURE_SEARCH_ENDPOINT}}
  AZURE_SEARCH_INDEX_NAME: {{.Env.AZURE_SEARCH_INDEX_NAME}}
  APPLICATIONINSIGHTS_CONNECTION_STRING: {{.Env.APPLICATIONINSIGHTS_CONNECTION_STRING}}
  VECTORDB_TYPE: {{.Env.VECTORDB_TYPE}}

