apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: creativeagent
  name:  afic
  annotations:
    azure.workload.identity/client-id: {{.Env.AZURE_AKS_IDENTITY_CLIENT_ID}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: afic
      containers:
        - name: api
          image: {{.Env.SERVICE_API_IMAGE_NAME}}
          ports:
            - containerPort: 5000
          env:
            - name: AZURE_OPENAI_API_VERSION
              value: {{.Env.AZURE_OPENAI_API_VERSION}}
            - name: AZURE_OPENAI_DEPLOYMENT_NAME
              value: {{.Env.AZURE_OPENAI_DEPLOYMENT_NAME}}
            - name: AZURE_OPENAI_35_TURBO_DEPLOYMENT_NAME
              value: {{.Env.AZURE_OPENAI_35_TURBO_DEPLOYMENT_NAME}}
            - name: AZURE_OPENAI_35_TURBO_DEPLOYMENT_NAME
              value: {{.Env.AZURE_OPENAI_35_TURBO_DEPLOYMENT_NAME}}
            - name: AZURE_OPENAI_ENDPOINT
              value: {{.Env.AZURE_OPENAI_ENDPOINT}}
            - name: BING_SEARCH_ENDPOINT
              value: {{.Env.BING_SEARCH_ENDPOINT}}
            - name: BING_SEARCH_KEY
              value: {{.Env.BING_SEARCH_KEY}}
            - name: AZURE_SEARCH_ENDPOINT
              value: {{.Env.AZURE_SEARCH_ENDPOINT}}
            - name: AZURE_SEARCH_INDEX_NAME
              value: {{.Env.AZURE_SEARCH_INDEX_NAME}}
            - name: VECTORDB_TYPE
              value: {{.Env.VECTORDB_TYPE}}
            - name: APPLICATIONINSIGHTS_CONNECTION_STRING
              value: {{.Env.APPLICATIONINSIGHTS_CONNECTION_STRING}}
          resources:
            requests:
              memory: "256Mi"
              cpu: "1000m" 
            limits:
              memory: "1024Mi"
              cpu: "2000m" 
