name: Validate AZD template
on:
  push:
    branches: [ aca-openai-agent ]
    paths:
      - "infra/**"
  pull_request:
    branches: [ aca-openai-agent ]
    paths:
      - "infra/**"

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Bicep for linting
        uses: azure/CLI@v1
        with:
          inlineScript: az config set bicep.use_binary_from_path=false && az bicep build -f infra/main.bicep --stdout

      - name: Run Microsoft Security DevOps Analysis
        uses: microsoft/security-devops-action@preview
        id: msdo
        continue-on-error: true
        with:
          tools: templateanalyzer

      - name: Upload alerts to Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: github.repository == 'Azure-Samples/contoso-creative-writer'
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}
